PressYourLuck/Controllers/AuditController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PressYourLuck.Helpers;
using PressYourLuck.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PressYourLuck.Controllers
{
    public class AuditController : Controller
    {
/*        private AuditContext _auditContext;
*/        public AuditController (/*AuditContext ctx*/)
        {
/*            this._auditContext = ctx;
*/        }

        [HttpGet()]
        public IActionResult CashIn (Player player)
        {
            Audit record = new Audit()
            {
                PlayerName = player.PlayerName,
                CreatedDate = DateTime.Now,
                Amount = player.CoinBalance,
                AuditTypeId = "ci"
            };
            /*_auditContext.Audits.Add(record);
            _auditContext.SaveChanges();*/
            return RedirectToAction("Index", "Home");
        }

        [HttpGet()]
        public IActionResult CashOut()
        {
            Audit record = new Audit()
            {
                PlayerName = GameHelper.GetPlayerName(HttpContext),
                CreatedDate = DateTime.Now,
                Amount = CoinsHelper.GetTotalCoins(HttpContext),
                AuditTypeId = "co"
            };

            /*_auditContext.Audits.Update(record);
            _auditContext.SaveChanges();*/

            GameHelper.ClearCurrentGame(HttpContext);
            HttpContext.Response.Cookies.Delete("playerName");
            HttpContext.Response.Cookies.Delete("total-coins");           

            return RedirectToAction("CreatePlayer", "Player");
        }

        [HttpGet()]
        public IActionResult Win()
        {
            double originalBet = CoinsHelper.GetOriginalBet(HttpContext);
            double currentCoins = CoinsHelper.GetCurrentBet(HttpContext);
            double winnings = currentCoins - originalBet;

            Audit record = new Audit()
            {
                PlayerName = GameHelper.GetPlayerName(HttpContext),
                CreatedDate = DateTime.Now,
                Amount = winnings,
                AuditTypeId = "w"
            };

            /*_auditContext.Audits.Update(record);
            _auditContext.SaveChanges();*/

            return RedirectToAction("Index", "Game");
        }

        [HttpGet()]
        public IActionResult Lose()
        {
            Audit record = new Audit()
            {
                PlayerName = GameHelper.GetPlayerName(HttpContext),
                CreatedDate = DateTime.Now,
                Amount = CoinsHelper.GetOriginalBet(HttpContext),
                AuditTypeId = "l"
            };

           /* _auditContext.Audits.Update(record);
            _auditContext.SaveChanges();*/

            return RedirectToAction("Index", "Game");
        }

       /* [HttpGet()]
        public IActionResult Index()
        {
            if (!HttpContext.Session.Keys.Contains("filter"))
                HttpContext.Session.SetString("filter", "all");
            else
                HttpContext.Session.SetString("filter", HttpContext.Request.Query["query"]);

            string tab = HttpContext.Session.GetString("filter");

            var model = new List<Audit>();
            var filter = new Filters(tab);
          
            if (filter.IsAll)
            {
                model = _auditContext.Audits.Include(a => a.auditTypes)                
                .OrderByDescending(a => a.CreatedDate)
                .ToList();
                Filters.CurrentTab = Filters.ActiveTab.All;
            }
            else if (filter.IsCashIn)
            {
                model = _auditContext.Audits.Include(a => a.auditTypes)
                .Where(a => a.auditTypes.Name == filter.FilterString)
                .OrderByDescending(a => a.CreatedDate)
                .ToList();
                Filters.CurrentTab = Filters.ActiveTab.CashIn;
            }
            else if (filter.IsCashOut)
            {
                model = _auditContext.Audits.Include(a => a.auditTypes)
                .Where(a => a.auditTypes.Name == filter.FilterString)
                .OrderByDescending(a => a.CreatedDate)
                .ToList();
                Filters.CurrentTab = Filters.ActiveTab.CashOut;
            }
            else if (filter.IsWin)
            {
                model = _auditContext.Audits.Include(a => a.auditTypes)
                .Where(a => a.auditTypes.Name == filter.FilterString)
                .OrderByDescending(a => a.CreatedDate)
                .ToList();
                Filters.CurrentTab = Filters.ActiveTab.Win;
            }
            else if (filter.IsLose)
            {
                model = _auditContext.Audits.Include(a => a.auditTypes)
                .Where(a => a.auditTypes.Name == filter.FilterString)
                .OrderByDescending(a => a.CreatedDate)
                .ToList();
                Filters.CurrentTab = Filters.ActiveTab.Lose;
            }

            List<string> currentTab = Filters.GetActiveTab();

            ViewBag.All = currentTab[0];
            ViewBag.CashIn = currentTab[1];
            ViewBag.CashOut = currentTab[2];
            ViewBag.Lose = currentTab[3];
            ViewBag.Win = currentTab[4];

            return View(model);
        }*/
    }
}

PressYourLuck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Press Your Luck</title>
    <link rel="icon" type="image/x-icon" href="~/images/PressYourLuck.ico" />
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav id="sharednav" class="navbar navbar-expand-md navbar-toggleable-md navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">Press Your Luck</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Audit" asp-action="Index" style="margin-top:0.7rem; font-size: 1.2rem;" asp-route-query="@Context.Session.GetString("filter")">Audit</a>
                        </li>
                        @if (string.IsNullOrEmpty(GameHelper.GetPlayerName(Context)))
                        {
                            <li class="nav-item" style="margin-left: 40rem">
                                <span class="nav-link text-white">Balance: $0.00</span>
                            </li>
                        }
                        else
                        {
                    <li class="nav-item" style="margin-left: 30rem; font-size: 1.3rem;">
                        <span id="balance" class="nav-link text-white">Balance: @CoinsHelper.GetTotalCoins(Context).ToString("C2")</span>
                    </li>
                        }
                        <li class="nav-item">
                            <a asp-action="CashOut" asp-controller="Player" class="btn btn-primary bg-success">Cash Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData.Keys.Contains("message"))
            {
                <div class="alert alert-info alert-dismissible text-bold" style="text-shadow: none !important; font-weight: bold">
                    <button class="close" data-dismiss="alert">&times;</button>
                    @TempData["message"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container text-black" style="margin-left:unset">
            &copy; 2021 - PressYourLuck by Andrew Macdonald 8738234
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>